Analise equipe fla re flavio monteiro rejanio moraes
DadosAbertosDeFeira/analises pull request #101
Opened 2021-03-10 16:37 UTC by Rejanio

Equipe: FlaRE
Participantes: Flávio Monteiro e Rejanio Moraes
Análise : O crescimento educacional da população está relacionado com o crescimento do trabalho formal?

Estrutura do trabalho: Pasta relatorio contém o arquivo .pdf explicando a análise. 
Pasta analysis tem os arquivos .py e jupyter .
Pasta data contém os arquivos .csv

2021-03-11 07:21 UTC, anapaulagomes commented
Olá, @Rejanio! Obrigada pela sua submissão. Vamos dar uma olhada e te damos um retorno. Terei que conversar com a organização sobre o caso de vocês porque a submissão foi feita fora do prazo e não comunicamos a outras equipes que elas poderiam fazer o mesmo. Dou um retorno assim que possível.

2021-03-12 01:19 UTC, Rejanio commented
Olá,

Sei que mandamos nossa análise fora do prazo, mas mesmo assim gostaríamos de ter um feedback da parte de vocês sobre o que fizemos. 
Para nós, mais importante que o prêmio é melhorar nossa capacidade como analistas de dados, e ajudar a cidade de alguma forma... 
Mediante a isso, peço que analise com calma o que fizemos e se possível nos dê um feedback e dicas de como podemos avançar nesse campo.
Mesmo que o mesmo seja extra oficial. 

Temos certeza que vindo de pessoas experientes na área, como você, o mesmo poderia nos ajudar a nos desenvolvermos cada vez mais...

Nos desculpe por qualquer transtorno causado 


Att, 

Flávio Monteiro e Rejanio Moraes 

Equipe Flare

2021-03-12 04:44 UTC, anapaulagomes commented
Oi, @Rejanio! Não se preocupem quanto a isso. Já havíamos passado pra as juradas e vamos dar um feedback pra vocês sim, claro. Não é transtorno algum. Na verdade, ficamos felizes que vocês resolvem enviar a análise! :)

2021-03-28 17:06 UTC, anapaulagomes requested changes
Olá, pessoal.

Obrigada pela contribuição! Enviamos para vocês um feedback por email.

Para que o PR seja aceito, precisamos que corrijam os erros do CI. Podem deletar o arquivo PDF também? Atentem que, para publicar a análise de vocês em nosso site (https://dadosabertosdefeira.github.io/analises/), vocês tem que gerar um HTML na pasta `docs/`. [Aqui](https://github.com/DadosAbertosDeFeira/analises/blob/main/.github/PULL_REQUEST_TEMPLATE/analysis_template.md#checklist) vocês encontram instruções para a submissão.

Vamos que vamos! 🚀

2021-04-02 01:26 UTC, Rejanio commented
> Olá, pessoal.
> 
> Obrigada pela contribuição! Enviamos para vocês um feedback por email.
> 
> Para que o PR seja aceito, precisamos que corrijam os erros do CI. Podem deletar o arquivo PDF também? Atentem que, para publicar a análise de vocês em nosso site (https://dadosabertosdefeira.github.io/analises/), vocês tem que gerar um HTML na pasta `docs/`. [Aqui](https://github.com/DadosAbertosDeFeira/analises/blob/main/.github/PULL_REQUEST_TEMPLATE/analysis_template.md#checklist) vocês encontram instruções para a submissão.
> 
> Vamos que vamos! rocket

Olá Ana,
retirei a pasta relatorio e já gerei o html. Eu estou com o problema no momento de passar no teste. A informação do erro é " os outputs não estão limpos", mesmo eu limpando a saída usando o 'All clear outputs'. Fiz um busca  por  soluções e não deu certo. Você poderia ajudar ? Poderia dizer o que pode ser? 
Agradeço desde já

2021-04-03 19:06 UTC, anapaulagomes commented
Oi, @Rejanio. Algumas coisas para mudar:

* Podem substituir os underscores por hífen, como no padrão, no nome do notebook? `2021-03-09-hackathon_analise_feira_equipe_flare_analise.ipynb`
* O último commit está modificando outros notebooks sem necessidade. Por favor, remova-os
* O notebook de vocês parece limpo. Provavelmente o teste está apontando erro dos outros que foram executados e commitados (`analysis/2020-03-28-anapaulagomes-camara-e-covid-19.ipynb` e `analysis/2020-06-13-anapaulagomes-despesas-da-camara.ipynb`). Para testar local, basta ativar o virtual environment, instalar as dependências e rodar `pytest`.

Espero que ajude! 🙏🏽

2021-04-06 01:17 UTC, Rejanio commented
> Oi, @Rejanio. Algumas coisas para mudar:
> 
>     * Podem substituir os underscores por hífen, como no padrão, no nome do notebook? `2021-03-09-hackathon_analise_feira_equipe_flare_analise.ipynb`
> 
>     * O último commit está modificando outros notebooks sem necessidade. Por favor, remova-os
> 
>     * O notebook de vocês parece limpo. Provavelmente o teste está apontando erro dos outros que foram executados e commitados (`analysis/2020-03-28-anapaulagomes-camara-e-covid-19.ipynb` e `analysis/2020-06-13-anapaulagomes-despesas-da-camara.ipynb`). Para testar local, basta ativar o virtual environment, instalar as dependências e rodar `pytest`.
> 
> 
> Espero que ajude! 🙏🏽

Olá @anapaulagomes , muito obrigado por sua ajuda. desfiz os commits que modificou os seus arquivos e consertei o nome dos meus arquivos. Já estava rodando os testes no meu ambiente virtual local e agora deu certo. Obrigado por suas dicas.

2021-04-09 09:18 UTC, anapaulagomes approved these changes
🎉

2021-04-09 09:18 UTC, merged