Adiciona analise de frequencia de palavras
DadosAbertosDeFeira/analises pull request #24
Opened 2020-07-14 17:22 UTC by Jkasnese

Adiciona analise de frequencia de palavras pros datasets de leis e diários. Pode ser usado pra outros datasets com alguma modificação também.

Por enquanto nada de interessante na análise de palavras, acho. Porém não tem coisas como lematização, o que poderia fazer com que surgisse termos interessantes nas palavras mais frequentes.

Minha ideia inicial era fazer uma coisa tipo isso: https://medium.com/turing-talks/introdu%C3%A7%C3%A3o-ao-processamento-de-linguagem-natural-com-baco-exu-do-blues-17cbb7404258

2020-09-10 06:52 UTC, guilhermelowa commented
Mas parece que remover aquelas que pegavam a referência da HEAD funcionaram pra esse aqui, @anapaulagomes . Que tá rodando a Action de converter! ;)

2020-09-14 08:43 UTC, anapaulagomes commented on .github/workflows/convert_to_python_script.yml
> -          ref: ${{ github.head_ref }}
Se essa modificação está funcionando aqui temos que abrir um novo PR com essa mudança e, depois que for mergeada, atualizar as demais branches.

2020-09-29 18:12 UTC, guilhermelowa commented
Depois do #41 esse aqui já tá pronto também, @anapaulagomes . Se puder dar uma revisada seria massa, @felipelfb

2020-09-29 18:45 UTC, anapaulagomes commented
Precisa fazer um pull das últimas modificações pra verificar se deu tudo certo, @guilhermelowa.

2020-10-14 14:29 UTC, anapaulagomes commented
Atenção: a branch principal foi atualizada para `main`.

2020-10-31 12:13 UTC, anapaulagomes requested changes
Excelente, @guilhermelowa! Estamos chegando perto do fim. 👍🏽 Essa análise vai ser ótima para outras explorações nesse sentido. No futuro outras pessoas poderão expandir o seu trabalho para atas, diários oficiais, licitações e mais.

2020-10-31 12:13 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    # Remove ponctuation, digits and whitespaces  # TODO documentação em pt-br
Faltou traduzir para português e remover esse `TODO`

2020-10-31 12:13 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    # Remove accents
Esse comentário não precisa porque a condição já deixa bem claro.

2020-10-31 12:13 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    # Remove stopwords
Esse trecho é melhor deixar em um método separado, pra ficar explícito o que está sendo feito.

2020-10-31 12:13 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +print(f"Numero de palavras unicas no text: {unique_words_count}")
```suggestion
print(f"Número de palavras únicas no texto: {unique_words_count}")
```

2020-10-31 12:13 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    custom_stopwords = [
Talvez seja melhor colocar todas as letras do alfabeto também. `d` e `n`, por exemplo, estão saindo na análise.

![índice](https://user-images.githubusercontent.com/1899950/97778817-1956a180-1b7a-11eb-933e-d09080fb0eb4.png)

2020-10-31 12:13 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    ]
Talvez seja interessante explicar o motivo dessas palavras terem sido escolhidas.
Lembro que discutimos sobre utilizar o `Counter` do Python pra visualizar as palavras mais comuns. Pensou nisso?

2020-10-31 18:15 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Estranho ^o) Não abriu aí? Aqui ficou direitinho na célula e abre direitinho se clico no link:

![Screenshot from 2020-10-31 15-14-41](https://user-images.githubusercontent.com/17838427/97786659-dac9e280-1b8b-11eb-8444-00f3fe580def.png)

2020-10-31 18:16 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# (https://www.kaggle.com/anapaulagomes/leis-do-municpio-de-feira-de-santana/).
A mesma resposta pra esse

2020-10-31 18:19 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Abre no Jupyter Notebook. Não vai renderizar correto.

2020-10-31 18:23 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    if isinstance(text, float):
É, tinha trocado a condição no outro e deixar passar nesse :X

Nesse caso é melhor colocar no `try / except`, como no `scripts/parsers.py`, ou chamar um `raise` se entrar no IF (não sei se existe essa opção)?

2020-10-31 18:25 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +        return ""
Valor mesmo? Pensei em colocar "Argumento recebido" ao invés de "Valor". É incomum?

2020-10-31 18:25 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    if isinstance(text, float):
Eu acho que com `if` + `raise` fica mais limpo e fácil de entender.

2020-10-31 18:29 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +print(f"Numero de palavras unicas no text: {unique_words_count}")
Não tem problema usar UTF-8? Não aparece estranho dependendo do terminal que a pessoa tá?

2020-10-31 18:31 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    custom_stopwords = [
Vou incluir `d`e `n` por hora. Depois que mergearmos o outro PR eu vou usar as stopwords definidas lá aqui

2020-10-31 18:41 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    ]
Lembro sim. Mas qual seria a vantagem de usar o Counter do Python, já que o FreqDist do nltk já faz essa função e principalmente disponibiliza pra gente um plot pronto?

Entendo que, se não usassemos o NLTK em outro lugar, poderíamos remover essa dependência. Mas já usamos o NLTK pra remover as stopwords.

2020-10-31 18:54 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Ah entendi. De fato no HTML não renderizou. O problema é que ele dá erro no .py se deixamos assim, sem quebrar a linha - linha muito longa. Não queria usar um encurtador de links.

Uma solução é deixar assim correto e com o link completo e depois quebrar a linha no .py. O que acha? Não é legal ficar fazendo na mão, mas acho melhor do que não renderizar no HTML ou usar um encurtador de links.

2020-10-31 19:40 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Nesse caso, é só adicionar `  # noqa` no final da linha, assim o linter vai ignorar a linha e seguir pra próxima. Daí você faz isso pra todos as linhas grandes demais que forem do markdown no arquivo Python.

2020-10-31 19:42 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
No final da linha adicione dois espaços antes da `#` (é uma boa prática).

2020-10-31 19:45 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +        return ""
Fica a gosto do freguês. :)

2020-10-31 19:47 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +print(f"Numero de palavras unicas no text: {unique_words_count}")
Até onde eu sei, não (ou não deveria).

2020-10-31 19:48 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    custom_stopwords = [
Beleza mas vamos evitar essa dependências análises da próxima (pra chegar o mais próximo de ter análises prontas mergeadas).
Se existem essas dependências é melhor mantê-las em um único PR.

2020-10-31 19:50 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    ]
Não, o Counter seria para ajudar na escolha das palavras que irão compor a lista de stop words.

2020-10-31 20:07 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Hmm, gostei! Mas nesse caso tb seria manualmente no .py né? Se eu colocar   `  # noqa` no markdown ele vai aparecer no texto. E aí em toda alteração tem que colocar isso no .py tb

2020-10-31 20:13 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    custom_stopwords = [
Tô ciente! Faria diferente os PRs se fosse hoje hahaha

2020-10-31 20:15 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Isso, só no `.py`. Podemos ver como tirar essa restrição da pasta de análises, assim não precisaríamos usar o `noqa`.

2020-10-31 20:18 UTC, anapaulagomes commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Aqui tem como fazer (opção `exclude`):
https://flake8.pycqa.org/en/latest/user/configuration.html

2020-10-31 20:26 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +        return ""
Acabei de receber um stacktrace e lembrei que gosto quando ele informa o esperado e o que recebeu. Troquei a mensagem pra:

`raise ValueError(f"Esperava string, recebido {type(text)}")`

2020-10-31 20:28 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +    ]
Ahh, ok! Tinha entendido errado então. Nesse caso, temos que rodar ele antes das stopwords, né? Vou fazer isso

2020-11-05 20:32 UTC, guilhermelowa commented on analysis/2020-10-23-guilhermelowa-textual-exploratory-analysis.py
> +# - [Como criar nuvem de palavras]
Acho que é uma boa opção, já que nesse caso atrapalha bastante. Vou abrir uma issue separada pra isso, pra resolver em outro PR, ok?

2020-11-06 11:12 UTC, anapaulagomes commented
@guilhermelowa precisa colocar o HTML na pasta `docs/notebooks`. Essa modificação foi feita recentemente (tem que atualizar a branch pra os testes mostrarem isso na mensagem de erro).

2020-11-06 19:41 UTC, guilhermelowa commented
> @guilhermelowa precisa colocar o HTML na pasta `docs/notebooks`. Essa modificação foi feita recentemente (tem que atualizar a branch pra os testes mostrarem isso na mensagem de erro).

Feito! A ideia então é todos os notebooks serem publicados?

2020-11-07 07:50 UTC, anapaulagomes commented
Sim, a ideia seria publicar os que tiverem algo para pessoas lerem e tal. A não ser que a pessoa não queira, @guilhermelowa.

2020-11-07 07:58 UTC, anapaulagomes approved these changes
Wohoo! 🎉 Obrigada pela contribuição, Gui. Vamos que vamos!

2020-11-07 07:58 UTC, merged