Adiciona analise dos pagamentos
DadosAbertosDeFeira/analises pull request #25
Opened 2020-07-14 17:27 UTC by Jkasnese

Algumas análises rápidas sobre os pagamentos.

Primeiro o processo de limpar os dados, que pode ser útil pra quem for analisar os pagamentos no futuro.

Depois, tô analisando outliers e tentando prever o valor dos pagamentos a partir de informações textuais.

Os outliers até então tô usando o método gaussiano e o LFO (que utiliza a densidade de exemplos próximos dos k vizinhos próximos). Vou conferir depois como é feita a Rosie do Serenata.

Pra prever o valor dos pagamentos vou fazer a princípio um regressor linear mesmo, pra estudar.

2020-09-29 20:40 UTC, guilhermelowa commented
Deu erro na formatação de setup.py. Não entendi por que. Primeiro que eu dei pull agora do master do repo original. Segundo, no commit 0d48815, rodei o pre-commit em todos os arquivos. Ainda assim, rodei o black no setup.py agora e reformatou o arquivo. Vou dar um push pra ver

2020-09-30 08:11 UTC, anapaulagomes commented
Sempre que aparece na mensagem do pre-commit que algo foi reformatado significa que você tem que adicionar e commitar novamente (se não fica nesse estado aí). Faz o pull e tenta de novo. A versão do black tem que ser fixada pra penúltima porque a última está com algumas inconsistências - talvez seja isso. Temos uma versão no requirements (a que você usou pra formatar o setup.py) e outra no pre-commit. Fiz a modificação da versão do black no pre-commit, vamos ver o que rola depois de você atualizar também.

2020-09-30 20:31 UTC, guilhermelowa commented
Eu tinha commitado novamente, sim. Só que aí aparecia que não tinha nada pra commitar. Provavelmente ele rearrumava o setup.py com a configuração que tinha no pre-commit. Seu update resolveu! (: :+1:

2020-10-01 19:47 UTC, guilhermelowa commented
Marquei como pronto, mas na verdade o teste do parser que eu criei me parece que não tá bom. Funciona, mas deve ter um jeito melhor de fazer isso. Só que eu sei tão pouco que não sei nem como buscar isso. 

Ver scripts/tests/test_parsers.py

2020-10-04 14:05 UTC, anapaulagomes requested changes
Bom começo! 🚀 

Deixei alguns comentários a respeito do script de limpeza e seus testes.
Ainda não olhei os notebooks - tô curiosa pra saber o porquê os scripts Python não foram gerados... Seria bom tê-los para a revisão.

2020-10-04 14:05 UTC, anapaulagomes commented on scripts/parsers.py
> +    except TypeError:
Acho que esse trecho nunca será executado porque você já descarta qualquer tipo que não é uma string.

2020-10-04 14:05 UTC, anapaulagomes commented on scripts/parsers.py
> +def limpa_proc_licitatorio(proc: str) -> str:
Tenho uma sugestão de reescrita desse método, de maneira que mantém a mesma essência mas com um pouco menos de código. Alguns dos porquês segue nos próximos comentários.

```suggestion
def limpa_procedimento_licitatorio(procedimento):
    """Limpa e normaliza o campo Processo Licitatório."""
    if not isinstance(procedimento, str):
        return

    isento = ["isento", "sento", "ento"]
    pregao = ["pregao", "regao", "egao"]
    dispensa = ["dispensa", "spensa", "ispensa", "pensa"]
    concorrencia = ["concorrencia", "oncorrencia", "ncorrencia", "concorencia"]
    inexigibilidade = [
        "inexigibilidade",
        "inexibilidade",
        "inegibilidade",
        "nexigibilidade",
        "xigibilidade",
        "exigibilidade",
    ]
    tomada_de_preco = ["tomada de preco", "omada de preco"]

    procedimento = procedimento.lower()

    if procedimento in isento:
        return "isento"
    if procedimento in pregao:
        return "pregao"
    if procedimento in dispensa:
        return "dispensa"
    if procedimento in concorrencia:
        return "concorrencia"
    if procedimento in inexigibilidade:
        return "inexigibilidade"
    if procedimento in tomada_de_preco:
        return "tomada de preco"
    return procedimento
```

2020-10-05 20:34 UTC, guilhermelowa commented on scripts/tests/test_parsers.py
> +    "proc_licitatorio_sujo,proc_licitatorio_limpo",
Certo! Qualquer coisa eu mudo, é rapidinho. Como tô fazendo os notebooks em português (e essa função tava no notebook) acabou ficando em português também

2020-10-05 20:36 UTC, guilhermelowa commented on scripts/tests/test_parsers.py
> +    "proc_licitatorio_sujo,proc_licitatorio_limpo",
Sobre a forma de escrever o teste, não tem um jeito melhor? Por exemplo, criar uma lista com todos as variações de "isento" e colocar a saída esperada ("isento") pra todas os elementos dessa lista? Assim como tá no parser

2020-10-05 20:39 UTC, guilhermelowa commented on scripts/parsers.py
> +    isento = ["ISENTO", "ENTO", "Isento", "SENTO", "sento"]
Sim. Eu peguei todas as possibilidades que aparecem no dataset. Talvez caiba gerar de verdade todas as possibilidades a 1 ou 2 edits de distância (já faço isso no notebook autocorrect no PR #27) e dizer que todas elas são isento. "ENTO" por ex tá há 2 edits de distância

2020-10-05 20:53 UTC, guilhermelowa commented on scripts/parsers.py
> +def limpa_proc_licitatorio(proc: str) -> str:
Acho que os próximos comentários apareceram antes aqui, né? Mas entendi sim as alterações! Já empurrei as alterações.

Uma coisa que não tinha pensado quando fiz esse parser é: como cobrir typos futuros no processo licitatório? Eu cobri só os que já existem. Como eu citei num comentário, o autocorret.ipynb no PR #27 contém uma função pra gerar todas as palavras a 2 edits de distância. Isso cobre quase todos os typos que já existem, com exceção de "xigibilidade" que precisa inserir 3 letras pra virar "inexigibilidade". Acho que seria uma função legal pra adicionar nesse parser.

Qual o melhor jeito de registrar essa pendência? Abrir uma Issue e explicar isso ou colocar um #TODO no começo do parser?

2020-10-07 09:18 UTC, anapaulagomes requested changes

2020-10-07 09:18 UTC, anapaulagomes commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
```suggestion
def limpa_processo_licitatorio(procedimento):
```

2020-10-07 09:18 UTC, anapaulagomes commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
Na verdade, `processo` é melhor, não? Procedimento parece outra coisa.

2020-10-07 09:18 UTC, anapaulagomes commented on scripts/parsers.py
> +    return procecimento
Aqui você está retornando o valor original ao invés de normalizado em minúsculo. Ou seja: se você retornar o original a sua análise pode ter problemas se for _case sensitive_ ou se tiver algum erro de digitação.

2020-10-07 09:19 UTC, anapaulagomes commented on scripts/tests/test_parsers.py
> +    "proc_licitatorio_sujo,proc_licitatorio_limpo",
Teria mas fica ruim pra ler. Da forma que está você pode tirar certas variações de maiúsculas e minúsculas pra enxugar um pouco mas, no geral, é um boa prática ter entradas explícitas nos testes.

2020-10-07 09:21 UTC, anapaulagomes commented on scripts/parsers.py
> +    isento = ["ISENTO", "ENTO", "Isento", "SENTO", "sento"]
Gui, isso é _overengineering_. A gente não vai conseguir cobrir todas as possibilidades, por isso é melhor trabalhar com o que já temos e apenas responder as mudanças que acontecerem quando elas acontecerem. O método que você desenvolveu já cobre 99% dos casos (até pq o esperado é que os typos sejam minorias).

2020-10-07 09:23 UTC, anapaulagomes commented on scripts/parsers.py
> +def limpa_proc_licitatorio(proc: str) -> str:
Nenhum dos dois, na minha opinião. Como comentei [aqui](https://github.com/DadosAbertosDeFeira/analises/pull/25#discussion_r500864693), isso seria se preparar demais pra uma situação que ainda não existe. Vamos manter simples por hora - ainda não temos um volume enorme de análises e nem de dados para algo assim. Além disso, a comunicação no projeto ainda é fácil; caso novos typos surjam, é só abrir um PR e show.

2020-10-07 09:24 UTC, anapaulagomes commented
PS.: @guilhermelowa para revisar os notebooks a gente precisa dos arquivos `.py`. Chegou ver o motivo de não estarem sendo gerados? A branch está atualizada?

2020-10-16 11:45 UTC, guilhermelowa commented on scripts/parsers.py
> +    isento = ["ISENTO", "ENTO", "Isento", "SENTO", "sento"]
_overengineering_ hahaha gostei. Nunca tinha ouvido falar. Faz sentido, sim! Gostei

2020-10-16 11:47 UTC, guilhermelowa commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
Acho que processo é melhor, baseado nas buscas que fiz no DuckDuckGo. Resultados melhores. Usei procedimento pq é esse o termo que tá no arquivo de despesas. Acho que já vem do crawler esse termo? Se sim, vou abrir um PR lá no Maria Quitéria (:

2020-10-16 11:58 UTC, guilhermelowa commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
Outra questão com inglês aqui. Pensei em traduzir de processo_licitatorio pra _bidding_process_, porém os campos do crawler vem em português, ex: "data_publicação, fase, credor, CNPJ" etc. Faz sentido jogar tudo pra inglês (mudar os crawlers) e construir um dicionário de inglês pra esses termos? Como procedemos nesse caso? Por hora vou escrever o código em inglês e deixar os campos do DataFrame em português, como vieram do crawler.

2020-10-16 12:01 UTC, guilhermelowa commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
E o type hint? Não faz sentido manter, já que a gente espera uma str de entrada?

2020-10-16 13:03 UTC, anapaulagomes commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
Os crawlers retornam os nomes em inglês desde sempre. Quando fiz upload dos dados mudei os nomes das colunas para facilitar o uso por jornalistas que não falam inglês mas acabou que os dados nem foram utilizados.

2020-10-16 13:05 UTC, anapaulagomes commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
Eu acho que não faz sentido usar type hints nesse caso (parece pela metade já que o projeto não adota e nem vai fazer nenhuma diferença).

2020-10-16 13:30 UTC, guilhermelowa commented on scripts/parsers.py
> +def limpa_processo_licitatorio(procecimento: str):
Saquei!

2020-10-17 11:26 UTC, guilhermelowa commented
Não sei o que há. A branch tá atualizada sim, no CI ele gera os .py, porém não commita. Na hora de commitar ele diz que não tem nada pra commitar. Reverti a mudança que tinha feito no CI de converter, agora ele nem rodou, só rodou o outro.

2020-10-17 15:09 UTC, anapaulagomes commented on .github/workflows/convert_to_python_script.yml
> +          ref: ${{ github.head_ref }}
Gui, estava aqui olhando a Action que faz isso e vi:

> By default, this Action will not run on Pull Requests which have been opened by forks. (This is a limitation by GitHub, not by us.)

https://github.com/stefanzweifel/git-auto-commit-action#using-the-action-in-forks-from-public-repositories

Dá uma lida e vamos discutir um pouco sobre isso.

2020-10-17 15:14 UTC, anapaulagomes commented on .github/workflows/convert_to_python_script.yml
> +          ref: ${{ github.head_ref }}
Outras alternativas além dessa Action:

* Criar um git hook: https://github.com/jupyterhub/jupyterhub/issues/1412
* Criar um teste unitário que verifica os nossos notebooks e falha se o script Python correspondente não for encontrado

2020-12-05 19:28 UTC, guilhermelowa commented
Não vou trabalhar neste PR no momento.

Existem algumas ideias e descobertas interessantes nessa análise, mas os dados da Prefeitura não são confiáveis, como discutido em #43 .

Podemos terminar a análise com os dados disponíveis e depois rodar com os dados mais corretos, no entanto surgiram outras prioridades no projeto.

Se alguém quiser tocar essa análise, seria ótimo!

2020-12-05 19:28 UTC, closed without merging