Adiciona config do pre-commit
DadosAbertosDeFeira/analises pull request #39
Opened 2020-09-04 19:29 UTC by guilhermelowa

Adiciona a configuração do pre-commit. Copiado do mária-quitéria.

2020-09-07 08:27 UTC, anapaulagomes requested changes
Bela contribuição! 🎉 Vai nos ajudar a deixar o código do repo de análises ainda melhores.

Senti falta de instruções para instalação do `pre-commit`. Não precisa ser um passo a passo mas uma menção ao menos ([como na Maria Quiteria](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/master/CONTRIBUTING.md#criando-pull-requests)).

Além disso, fiquei curiosa pra saber: chegou a ver algo sobre pre-commit hooks e Jupyter notebooks? A issue menciona um projeto. Chegou a testar? Se sim, como foi?

2020-09-07 08:27 UTC, anapaulagomes commented on .pre-commit-config.yaml
> +    -   id: check-added-large-files
No nosso CI temos rodando o flake8 e o black. É esperado que o pre-commit também tenha os dois ([assim como na Maria Quiteria](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/master/.pre-commit-config.yaml)) pq o objetivo dele é pegar os possíveis problemas antes do código ser pushado.

Além do black e do flake8, apesar de não estar no CI ainda, ter o isort também é bem interessante.

2020-09-07 08:27 UTC, anapaulagomes commented on .pre-commit-config.yaml
> +# See https://pre-commit.com for more information
Esses comentários podem ser apagados.

2020-09-07 19:44 UTC, guilhermelowa commented on .pre-commit-config.yaml
> +    -   id: check-added-large-files
Ué, que estranho. Eu tinha copiado esse arquivo de config do maria quitéria ^o) Desculpe, erramos. Vou tentar novamente e adicionar o isort

2020-09-07 20:03 UTC, guilhermelowa commented
Pronto! Adicionei a menção ao pre-commit e consertei a referência do repositório do pre-commit-hooks. Mas ainda assim, tá dando erro no CI de Notebook pra Python, só que não tem nenhum notebook novo nessa branch. 

Vou dar uma olhada. O erro tá aqui:

```
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/adiciona_precommit_config*:refs/remotes/origin/adiciona_precommit_config* +refs/tags/adiciona_precommit_config*:refs/tags/adiciona_precommit_config*
  The process '/usr/bin/git' failed with exit code 1
```

- - - 

Sobre o pre-commit do Jupyter, ainda não olhei. Assim que consertar isso eu vejo

2020-09-07 20:23 UTC, guilhermelowa commented
Não achei informação sobre exit code 1. Mas lendo os comandos do CI, acho estranho isso aqui:

```
 with:
    ref: adiciona_precommit_config
    repository: DadosAbertosDeFeira/analises
```

E aí ele vai dar erro no seguinte comando:

```
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/adiciona_precommit_config*:refs/remotes/origin/adiciona_precommit_config* +refs/tags/adiciona_precommit_config*:refs/tags/adiciona_precommit_config*
  The process '/usr/bin/git' failed with exit code 1
```

Ele tá procurando a head "adiciona_precommit_config" no repositório DadosAbertosDeFeira/analises?

2020-09-07 21:02 UTC, guilhermelowa commented
Hook do Jupyter:

Ele tem uma incompatibilidade com o hook de inserir uma linha em branco no final do arquivo. Mesmo colocando o hook do Jupyter antes e o do final do arquivo depois, não adiciona uma linha no final do arquivo. Não entendi por quê.

2020-09-08 08:20 UTC, anapaulagomes commented on CONTRIBUTING.md
> +* Instale o _pre-commit_ localmente. Rode o _pre-commit_ antes de _commitar_ seu código. Dessa forma, o código _commitado_ já estará formatado, com os _imports_ ordenados e mais arrumado.
```suggestion
* Instale o _pre-commit_ localmente com `pre-commit install`. Da próxima vez que você foi criar um _commit_ as verificações serão executadas automaticamente.
Caso exista alguma falha na formatação você será informado e o _commit_ só será permitido após correção (alguns linters como o _isort_ já fazem a correção automaticamente mas ainda é necessário _commitar_ novamente.
Dessa forma mantemos o código mais arrumado.
```

2020-09-08 08:22 UTC, anapaulagomes commented
Gui, remove essa parte do [workflow](https://github.com/DadosAbertosDeFeira/analises/blob/master/.github/workflows/convert_to_python_script.yml) e commita pra gente fazer um teste:

```
with:
    ref: ${{ github.head_ref }}
```

2020-09-08 18:00 UTC, guilhermelowa commented on CONTRIBUTING.md
> +* Instale o _pre-commit_ localmente. Rode o _pre-commit_ antes de _commitar_ seu código. Dessa forma, o código _commitado_ já estará formatado, com os _imports_ ordenados e mais arrumado.
Ué, roda automaticamente? Fiz alguma besteira então.. Talvez não instalei pelo venv? Eu tenho que rodar manualmente aqui depois do git add. Vou tentar re-instalar o pre-commit pelo venv pra ver se vai automático

2020-09-09 12:50 UTC, anapaulagomes commented on CONTRIBUTING.md
> +* Instale o _pre-commit_ localmente. Rode o _pre-commit_ antes de _commitar_ seu código. Dessa forma, o código _commitado_ já estará formatado, com os _imports_ ordenados e mais arrumado.
Isso, tem que instalar no seu virtual environment. É uma dependência normal (inclusive, tem que adicioná-la no `requirements.txt`). Os passos são:

0. Ativar o virtual environment
1. Instalar o pacote do pre-commit (`pip install pre-commit`)
2. Instalar o hook do pre-commit (`pre-commit install`)
3. Testar se está funcionando: faz alguma modificação que deveria ser captada por algum dos linters e adiciona ao git (`git add arquivo`) sem commitar. Então executa `pre-commit`.

Depois que estiver configurado e funcionando bonitinho nenhum desses passos são necessários. Ao tentar criar um commit os linters serão executados automaticamente, sem nenhum comando extra.

2020-09-10 06:11 UTC, guilhermelowa commented on CONTRIBUTING.md
> +* Instale o _pre-commit_ localmente. Rode o _pre-commit_ antes de _commitar_ seu código. Dessa forma, o código _commitado_ já estará formatado, com os _imports_ ordenados e mais arrumado.
Ahh ok. Acho que faltou o passo 2 pra mim. Agora foi! \o/

2020-09-10 06:32 UTC, guilhermelowa commented
Olha, acho que agora foi, mas acho que ele não rodou o workflow: Converte Notebook pra script Python. O que acho que é o comportamento esperado, né? Já que nenhum notebook foi modificado nessa branch.

O que tinha acontecido foi: mudei meu nome no GitHub e não atualizou a referência pro meu fork no repo local. Aí não tava dando o pull direito. Não entendi isso muito bem, já que eu tava conseguindo dar push. Como é que o push funcionava e o pull não? Enfim...

Pelo visto a run do commit "Adiciona pre-commit ao requirements.txt - 66fc8a9" rodou. Recebi um email de erro, mas era na outra branch. Então vou reverter esse último fix e ver se rola.

2020-09-10 06:43 UTC, guilhermelowa commented
Como é que eu faço esse reset de um jeito melhor, sem precisar dar force-push? Relaxe, vou olhar isso melhor amanhã, tô só documentando.

Eu fiz:
``` 
git reset --hard HEAD^ # Pra voltar 1 commit
git push # Deu erro pq tava um commit atrás
git push -f # Foi, mas aí é forçado.
```

Como eu faço esse último push sem forçar, já que eu tô essencialmente voltando um commit? Ou seja, o que eu quero empurrar de fato é 1 atrás do repositório mesmo.

2020-09-14 08:56 UTC, anapaulagomes commented
Não entendi o que tu quer fazer, @guilhermelowa. 🤔 Pelo que vi no teu fork, tua branch está desatualizada. O ideal seria sua branch estar atualizada, com os conflitos resolvidos. Aí se você precisar pode fazer um rebase interativo: deletar commits, mergear commits etc. Meu conselho seria: atualiza a branch, resolve os conflitos e ver como fica - o PR traz atualizações muito pequenas e o principal é um arquivo novo... Não deveria ficar tão complexo assim.

2020-09-28 23:27 UTC, guilhermelowa commented
Pois é, também não entendi. Tá dizendo que as histórias não são relacionadas. Não entendi por que. Deve ser aquele problema de trocar o nome no GitHub que te falei, aí deve ter perdido referência, não sei.

Posso excluir essa aqui e criar outro PR igual em outra branch? Acho que é o mais simples

2020-09-28 23:29 UTC, guilhermelowa commented
Pois é, também não entendi. Tá dizendo que as histórias não são relacionadas. Não entendi por que. Deve ser aquele problema de trocar o nome no GitHub que te falei, aí deve ter perdido referência, não sei.

Posso excluir essa aqui e criar outro PR igual em outra branch? Acho que é o mais simples

2020-09-29 09:15 UTC, anapaulagomes commented on CONTRIBUTING.md
> +* Instale o _pre-commit_ localmente. Rode o _pre-commit_ antes de _commitar_ seu código. Dessa forma, o código _commitado_ já estará formatado, com os _imports_ ordenados e mais arrumado.
Faltou corrigir o texto dessa parte aqui.

2020-09-29 09:17 UTC, anapaulagomes commented
De todo jeito, aqui você precisa fazer o rebase, tanto pra pegar a última atualização quanto para resolver o conflito do requirements.

2020-09-29 18:06 UTC, guilhermelowa commented
Mesmo depois do rebase não consegui dar o push (`the tip of your current branch is behind`) e nem o pull (`fatal: refusing to merge unrelated histories`). Aí forcei o push... ):

2020-09-29 18:42 UTC, anapaulagomes approved these changes
SHOW ROGERINHO! 👍🏽

2020-09-29 18:42 UTC, merged