62 Criar um notebook base para análise de dados do TSE
DadosAbertosDeFeira/analises pull request #66
Opened 2020-11-04 17:25 UTC by vihvs

Esse PR inclui um notebook template com instruções básicas de como analisar dados adquiridos no site do TSE relacionados aos candidatos a eleição.
Foi incluida uma pasta 'templates' para separar esse notebook de análises.

2020-11-04 18:16 UTC, anapaulagomes commented
Excelente, @vihvs! 🚀 Tem dois notebooks com o mesmo nome em pastas diferentes. É isso mesmo?

2020-11-04 18:24 UTC, vihvs commented
Não 😂
Achei que tinha só colocado um em stage. Vou atualizar ✌️

Ana Paula Gomes <notifications@github.com> schrieb am Mi., 4. Nov. 2020,
19:16:

> Excelente, @vihvs <https://github.com/vihvs>! 🚀 Tem dois notebooks com o
> mesmo nome em pastas diferentes. É isso mesmo?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DadosAbertosDeFeira/analises/pull/66#issuecomment-721893173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABW77XDJRPMJMRD3G3EP4CLSOGK7LANCNFSM4TKKSD4Q>
> .
>

2020-11-04 19:59 UTC, anapaulagomes requested changes
Muito massa, @vihvs! 🏆 Só tenho duas observações:

1) Será que daria pra substituir underscore por hífen no nome do notebook? Assim a gente segue o padrão de nomes dos outros notebooks do repo
2) O que acha de colocar a seção "Unir tabelas do TSE" por último? Ela parece ser mais "avançada" comparada com as outras
3) Pode também, por favor, adicionar `templates` no nosso README (temos uma seção chamada [estrutura](https://github.com/DadosAbertosDeFeira/analises#estrutura))

Depois disso estamos prontos pra mergear (ignore o CI - o bot não funciona pq o PR veio de um fork 💔 ).

2020-11-04 21:16 UTC, vihvs commented
Percebi sobre o CI 😞 
Enfim, vou fazer as mudanças, só discordo da questão da ordem do merge. Eu montei inicialmente da maneira que você sugeriu, porém ficou muito 'escondido' e meio fora de ordem. Porque a pessoa primeiro prepara a tabela unificada e depois analisa. Mas você tem razão que é um ponto mais avançado mesmo.

2020-11-04 22:09 UTC, anapaulagomes commented
@vihvs, eu pensei que daria pra montar o base usando apenas um arquivo (pq aí não usaria o merge logo no início, por exemplo). Mas foi só uma sugestão. De toda forma, é bastante útil. Fica a teu critério!
Me dá um toque se já estiver pronto pra revisão novamente.

2020-11-05 08:10 UTC, anapaulagomes commented on README.md
> +* `publish`: arquivos prontos para serem publicados e divulgados
```suggestion
```

Essa linha não existe mais (foi removida porque agora as publicações acontecem em `docs/` - pasta obrigatória para publicação no Github Pages).

2020-11-05 08:10 UTC, anapaulagomes commented
Removi o bot do CI, então agora deve funcionar. 🙏🏽

2020-11-06 08:31 UTC, anapaulagomes approved these changes
Show demais, @vihvs! 🏆

2020-11-06 08:32 UTC, merged